# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0002_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemFirst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='market.Item')),
                ('itemSecond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='market.Item')),
                ('userFirst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('userSecond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
