# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 16:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0004_auto_20161223_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='tradeitems',
            name='itemFirst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='market.Item'),
        ),
        migrations.AlterField(
            model_name='tradeitems',
            name='itemSecond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='market.Item'),
        ),
    ]
