# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20161225_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackbox',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Item'),
        ),
        migrations.AlterField(
            model_name='tradeitems',
            name='itemFirst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='market.Item'),
        ),
        migrations.AlterField(
            model_name='tradeitems',
            name='itemSecond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='market.Item'),
        ),
    ]
